print('='*5,'DESAFIO 4','='*5)
n1 = input('DIGITA ALGO: ')
print(type(n1))
print('So tem Número:',n1.isnumeric())
print('Só tem Letra:',n1.isalpha())
print('Letra ou número:',n1.isalnum())
print('Letra maiúscula:',n1.isupper())
print('Letra minúscula:',n1.islower())
print('So tem espaço:',n1.isspace())